### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by chendd14** [petergaal/JpegRtspCamera#1]
I'm a beginner in video streaming develop, would you please tell me, how did you transform an encoded jpeg frame to video stream?

**Comment by petergaal** [comment]
If you are asking about how it is transformed to RTSP format then I think it's best to study the JpegFrameParser class (in src folder). It's not directly a jpeg file format but it is similar. If I remember correctly It's using some standard quantization tables which are not in the protocol (they are in the file headers but not transported in RTSP). The rest should be very similar to standard jpeg file. 
This part was quite hard to understand and I made lot of trials until it worked correctly.
