### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jodyngo** [petergaal/JpegRtspCamera#2]
I built it on VS 2015, opencv 3.0, Windows 8. and get below errors, please advise how to fix it

Error	LNK2001	unresolved external symbol __imp_WSAGetLastError

**Comment by petergaal** [comment]
Are you linking against ws2_32.lib in your project (Linker->Input->Additional dependencies in project properties)?

**Comment by jodyngo** [comment]
Dear sir,
I have resolved all problem.
Since I am a newbie in video streaming area, would you mind advise me how to start streaming video from PC webcams (on windows) to android phone using your source code. I am thankful if you advise the proper direction where I should begin to understand the whole process.

Thank you very much.

**Comment by petergaal** [comment]
Unfortunately I don't have experience with android, but VLC player should work on android without problem. You have to be in the same network (same wifi maybe). You can use PC as an RTSP server with my source code. Just feed a video signal from camera as an input and that should work (I tested this source code exactly this way). Maybe in a future (when you will understand the details) switch from JPEG  to H.264 codec to save bandwidth (but that's more complicated).
