### ISSUE TITLE
Grab H264

### ISSUE THREAD

**Issue by AndreWicked** [petergaal/JpegRtspCamera#3]
Hello! Thanks for this repository, it helped me a lot. 

I was able to run it on the Windows10 Qt5 OpenCv4 Live555 with the MSVC15 compiler. Everything works perfectly!
Could you tell me how I can get the H264 stream from an IP camera instead of a USB camera?

I would be very grateful for your help, thanks in advance!

**Comment by petergaal** [comment]
Hi Andrew.
I am glad you are able to run this project without problem.

You have more options depending on the camera. I don't remember it exactly from memory but you can grab over RTSP protocol. Examples are available in Live555 project. You can try to run and debug the OpenRTSP project. That will demonstrate how it works and it's also a very useful from getting H264 streams from RTSP cameras. Getting it over H264 is not that easy but I have done it in the past so it is possible.
Some cameras have a support for getting H264 over HTTP protocol. That is quite simple.

**Comment by petergaal** [comment]
Actually you can see also in my other project how to do it: https://github.com/petergaal/RtspToTCP 
This one is reading exactly an H264 stream from IP cameras and streams it over TCP protocol (without any headers).

I hope that helps.
