### ISSUE TITLE
How to build in Linux Environment 

### ISSUE THREAD

**Issue by hongson23** [petergaal/JpegRtspCamera#4]
hello,
Thank you for your works!

I would like to build your project under Linux system but I have some issue such as: 
![image](https://user-images.githubusercontent.com/4011696/97405102-b969bc00-1929-11eb-91f6-035d709a9e3a.png)

Can you help me resolved thoes problems?

**Comment by libo1712** [comment]
This is the difference between VS and GCC compiler.
You can You can modify JPEGMediaSubsession.hh to :
`virtual FramedSource* createNewStreamSource(unsigned clientSessionId, unsigned& estBitrate);
  virtual RTPSink* createNewRTPSink(Groupsock* rtpGroupsock, unsigned char rtpPayloadTypeIfDynamic, FramedSource* inputSource);`
Hope it works !

**Comment by hongson23** [comment]
> This is the difference between VS and GCC compiler.
> You can You can modify JPEGMediaSubsession.hh to :
> `virtual FramedSource* createNewStreamSource(unsigned clientSessionId, unsigned& estBitrate); virtual RTPSink* createNewRTPSink(Groupsock* rtpGroupsock, unsigned char rtpPayloadTypeIfDynamic, FramedSource* inputSource);`
> Hope it works !

Thank @libo1712 ,

It works correctly!

**Comment by tuanphan1790** [comment]
Hi, I've already got an error when building with Ubuntu 18.04.
Firstly, I made Live555, after that, I created a CMakeLists file and link to this library in the "usr/local/library" folder. But I got errors like this:

`OnDemandServerMediaSubsession.cpp:(.text+0x29c): undefined reference to `NoReuse::NoReuse(UsageEnvironment&)'
OnDemandServerMediaSubsession.cpp:(.text+0x374): undefined reference to `NoReuse::~NoReuse()'
OnDemandServerMediaSubsession.cpp:(.text+0x37c): undefined reference to `Groupsock::removeAllDestinations()'
OnDemandServerMediaSubsession.cpp:(.text+0x384): undefined reference to `Groupsock::removeAllDestinations()'
OnDemandServerMediaSubsession.cpp:(.text+0x394): undefined reference to `NoReuse::NoReuse(UsageEnvironment&)'
OnDemandServerMediaSubsession.cpp:(.text+0x408): undefined reference to `NoReuse::~NoReuse()'
OnDemandServerMediaSubsession.cpp:(.text+0x410): undefined reference to `Groupsock::removeAllDestinations()'
OnDemandServerMediaSubsession.cpp:(.text+0x43c): undefined reference to `increaseSendBufferTo(UsageEnvironment&, int, unsigned int)'
OnDemandServerMediaSubsession.cpp:(.text+0x55c): undefined reference to `NoReuse::~NoReuse()'
/usr/local/lib/libliveMedia.a(OnDemandServerMediaSubsession.o): In function `OnDemandServerMediaSubsession::createGroupsock(in_addr const&, Port)':
OnDemandServerMediaSubsession.cpp:(.text+0x5c8): undefined reference to `Groupsock::Groupsock(UsageEnvironment&, in_addr const&, Port, unsigned char)'
/usr/local/lib/libliveMedia.a(OnDemandServerMediaSubsession.o): In function `OnDemandServerMediaSubsession::OnDemandServerMediaSubsession(UsageEnvironment&, unsigned char, unsigned short, unsigned char)':
OnDemandServerMediaSubsession.cpp:(.text+0x828): undefined reference to `HashTable::create(int)'
/usr/local/lib/libliveMedia.a(ProxyServerMediaSession.o): In function `ProxyServerMediaSession::createGroupsock(in_addr const&, Port)':
ProxyServerMediaSession.cpp:(.text+0x70): undefined reference to `Groupsock::Groupsock(UsageEnvironment&, in_addr const&, Port, unsigned char)'
/usr/local/lib/libliveMedia.a(BasicUDPSource.o): In function `BasicUDPSource::BasicUDPSource(UsageEnvironment&, Groupsock*)':
BasicUDPSource.cpp:(.text+0x170): undefined reference to `increaseReceiveBufferTo(UsageEnvironment&, int, unsigned int)'
BasicUDPSource.cpp:(.text+0x17c): undefined reference to `makeSocketNonBlocking(int)'
/usr/local/lib/libliveMedia.a(MPEG2TransportStreamFramer.o): In function `MPEG2TransportStreamFramer::MPEG2TransportStreamFramer(UsageEnvironment&, FramedSource*)':
MPEG2TransportStreamFramer.cpp:(.text+0xb0): undefined reference to `HashTable::create(int)'
/usr/local/lib/libliveMedia.a(RTPSource.o): In function `RTPReceptionStatsDB::reset()':
RTPSource.cpp:(.text+0x234): undefined reference to `HashTable::Iterator::create(HashTable const&)'
/usr/local/lib/libliveMedia.a(RTPSource.o): In function `RTPReceptionStatsDB::RTPReceptionStatsDB()':
RTPSource.cpp:(.text+0x2e8): undefined reference to `HashTable::create(int)'
/usr/local/lib/libliveMedia.a(RTPSource.o): In function `RTPReceptionStatsDB::Iterator::Iterator(RTPReceptionStatsDB&)':
RTPSource.cpp:(.text+0x4d0): undefined reference to `HashTable::Iterator::create(HashTable const&)'
/usr/local/lib/libliveMedia.a(MultiFramedRTPSource.o): In function `MultiFramedRTPSource::MultiFramedRTPSource(UsageEnvironment&, Groupsock*, unsigned char, unsigned int, BufferedPacketFactory*)':
MultiFramedRTPSource.cpp:(.text+0x27c): undefined reference to `increaseReceiveBufferTo(UsageEnvironment&, int, unsigned int)'
/usr/local/lib/libliveMedia.a(RTCP.o): In function `RTCPInstance::incomingReportHandler1()':
RTCP.cpp:(.text+0x988): undefined reference to `Groupsock::wasLoopedBackFromUs(UsageEnvironment&, sockaddr_in&)'
/usr/local/lib/libliveMedia.a(RTCP.o): In function `RTCPMemberDatabase::reapOldMembers(unsigned int)':
RTCP.cpp:(.text+0xd2c): undefined reference to `HashTable::Iterator::create(HashTable const&)'
/usr/local/lib/libliveMedia.a(RTCP.o): In function `RTCPInstance::RTCPInstance(UsageEnvironment&, Groupsock*, unsigned int, unsigned char const*, RTPSink*, RTPSource*, unsigned char)':
RTCP.cpp:(.text+0x1610): undefined reference to `Groupsock::multicastSendOnly()'
RTCP.cpp:(.text+0x1668): undefined reference to `HashTable::create(int)'
/usr/local/lib/libUsageEnvironment.a(HashTable.o): In function `HashTable::RemoveNext()':
HashTable.cpp:(.text+0x68): undefined reference to `HashTable::Iterator::create(HashTable const&)'
/usr/local/lib/libUsageEnvironment.a(HashTable.o): In function `HashTable::getFirst()':
HashTable.cpp:(.text+0xfc): undefined reference to `HashTable::Iterator::create(HashTable const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/RTSPTest.dir/build.make:179: recipe for target 'RTSPTest' failed
make[2]: *** [RTSPTest] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/RTSPTest.dir/all' failed
make[1]: *** [CMakeFiles/RTSPTest.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
`

Can you help me resolve this problem?
